In [1]:
import duckdb

# connect to your database
con = duckdb.connect('../data/warehouse_new.duckdb')  # adjust path if needed

In [2]:
data = con.sql("SELECT * FROM merged_sales_customers_clean").fetchdf()
data

,meterid,customer_no,od_date,ocd_paymoney,ocd_energy,ocd_cash_received,utility,tariff_type
0,10010284581,501001387012,2012-10-25,6.00,30.14,6.0,Techiman,Residential
1,11010003761,501001392093,2013-02-15,12.00,64.54,12.0,Techiman,Residential
2,11010003761,501001392093,2013-06-01,23.00,146.19,23.0,Techiman,Residential
3,11010003761,501001392093,2013-09-30,23.19,147.60,145.0,Techiman,Residential
4,11010003761,501001392093,2013-07-27,23.00,156.48,23.0,Techiman,Residential
...,...,...,...,...,...,...,...,...
5100388,14012630651,503001441804,2020-07-24,30.00,30.70,30.0,Kintampo,Non Residential
5100389,14012630651,503001441804,2020-07-02,160.00,148.80,50.0,Kintampo,Non Residential
5100390,14012630651,503001441804,2020-09-10,30.00,30.70,30.0,Kintampo,Non Residential
5100391,14012630651,503001441804,2020-09-04,30.00,30.70,30.0,Kintampo,Non Residential
5100392,14012630651,503001441804,2020-09-01,30.00,15.80,30.0,Kintampo,Non Residential

In [3]:
data.columns

Index(['meterid', 'customer_no', 'od_date', 'ocd_paymoney', 'ocd_energy',
       'ocd_cash_received', 'utility', 'tariff_type'],
      dtype='object')

In [4]:
data[['meterid', 'customer_no', 'od_date', 'ocd_energy', 'ocd_cash_received', 'utility', 'tariff_type']]

,meterid,customer_no,od_date,ocd_energy,ocd_cash_received,utility,tariff_type
0,10010284581,501001387012,2012-10-25,30.14,6.0,Techiman,Residential
1,11010003761,501001392093,2013-02-15,64.54,12.0,Techiman,Residential
2,11010003761,501001392093,2013-06-01,146.19,23.0,Techiman,Residential
3,11010003761,501001392093,2013-09-30,147.60,145.0,Techiman,Residential
4,11010003761,501001392093,2013-07-27,156.48,23.0,Techiman,Residential
...,...,...,...,...,...,...,...
5100388,14012630651,503001441804,2020-07-24,30.70,30.0,Kintampo,Non Residential
5100389,14012630651,503001441804,2020-07-02,148.80,50.0,Kintampo,Non Residential
5100390,14012630651,503001441804,2020-09-10,30.70,30.0,Kintampo,Non Residential
5100391,14012630651,503001441804,2020-09-04,30.70,30.0,Kintampo,Non Residential
5100392,14012630651,503001441804,2020-09-01,15.80,30.0,Kintampo,Non Residential

In [7]:
data['ocd_paymoney'].sum(), data['ocd_paymoney'].mean()

(298250268.35, 58.47593868746977)

In [8]:
data['ocd_cash_received'].sum(), data['ocd_cash_received'].mean()

(296231889.27000004, 58.080208578044875)